definitions:
  requests.UserRequest:
    properties:
      created_time:
        type: string
      deleted_time:
        type: string
      email:
        type: string
      is_deleted:
        type: boolean
      name:
        type: string
      password:
        type: string
      role:
        type: string
      updated_time:
        type: string
    type: object
  responses.BaseResponse:
    properties:
      Data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /registry:
    post:
      consumes:
      - application/json
      description: create new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/requests.UserRequest'
      summary: create new user
      tags:
      - Authentication
  /report/get_all:
    get:
      description: return all report from database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.BaseResponse'
      summary: get all reports
      tags:
      - Reports
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
